# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e53c2e1e76af102a323c54a94a6a155f43d626f7d4de8437af1e07faf5783a2b691da27a9472f804116076fbe1ddf06ade7769ba38cd44619fe808d622ca2fe

test:
  secret_key_base: 966d805b6ffff3495a24f1bc2d5b6b7a6115cc4eaa1da0808aa1115f6f37725b06bd0476e7f8709fab88d1b89ab2c90c1fa62e90750dbff295674e3f16d56a6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
